name: Docker build for OpenLEADR Python

on:
  pull_request:
    branches:
      - master

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build Docker 3.7 image
        run: cd 3.7/ && docker build -t 3.7 .
